### ISSUE TITLE
V6 Release - Plan & Feedback

### ISSUE THREAD

**Issue by JohnnyCrazy** [JohnnyCrazy/SpotifyAPI-NET#451]
# TODO

* [x] Implement all Spotify Endpoints
    * [x] Search API
    * [x] Browse API
    * [x] Follow API
    * [x] Playlists API
    * [x] Library API
    * [x] Artists API
    * [x] Player API
    * [x] Personalization API
    * [x] User Profile API
    * [x] Albums API
    * [x] Tracks API
    * [x] Episodes API
    * [x] Shows API
* [x] Inline XML Docs with Links to Spotify API Docs
* [x] Implement `SimpleRetryHandler` based on the current implementation
	* [x] `RetryAfter` milliseconds
    * [x] `RetryErrorCodes`
    * [x] Maximum number of retries per request `RetryTimes`
    * [x] Tests
* [x] Implement `ProxyConfig` replacement
* [x] Update online Documentation and try to make it versionable (Version dropdown)
* [x] Implement Spotify.Web.Auth
	* [x] Update to latest EmbedIO
    * [x] Make it easier to supply Resources (HTML/JS/CSS)
* [ ] Implement Examples
	* [x] ASP.NET - SSR
	* [x] ASP.NET - Blazor in Browser (?)
	* [x] Console Client
    * [x] UWP
	* [ ] Xamarin (?)
	* [ ] Xamarin.Android (?)
* [x] TokenSwap Auth + NodeJS Example Server

Notes:

* Release first beta when all clients are implemented to gather feedback early, but docs have to be updated by then

**Comment by JohnnyCrazy** [comment]
V6 has been released - ⬇️ feedback thread

**Comment by YettySpaghetty** [comment]
When trying to call var following = await spotify.Follow.OfCurrentUser(), it breaks with SpotifyAPI.Web.APIException: 'No type given'. 

I assume it's because not type (either User or Artist) was provided for the request. I can't seem to find how pass the type anywhere although the OfCurrentUser() method does take one overload.
